### ISSUE TITLE
Training on selected subset of Dask DataFrame rows

### ISSUE THREAD

**Issue by mrphilroth** [dask/dask-xgboost#11]
In order to do CV iterations, I'd like to load all the data into a Dask DataFrame, select a subset of rows, and then train only on those selected rows. I've written some code that does this and it works when I use a ```LocalCluster```. When I try and use a true distributed cluster, I get an error when constructing the worker_map:

```
Traceback (most recent call last):
  File "/home/proth/.conda/envs/dask/lib/python3.5/site-packages/dask_xgboost/core.py", line 116, in _train
    worker_map[first(workers)].append(key_to_part_dict[key])
  File "/home/proth/.conda/envs/dask/lib/python3.5/site-packages/toolz/itertoolz.py", line 368, in first
    return next(iter(seq))
StopIteration
```

I tried to write a test that demonstrates this behavior, but the test passes. This makes me think that ```distributed.utils_test.gen_cluster``` uses a ```LocalCluster```. Is there anyway to run this test with a true distributed cluster?

```
@gen_cluster(client=True, timeout=None)
def test_subset(c, s, a, b):
    # Train in xgboost with selected data
    dtrain = xgb.DMatrix(df[df.x < 8], label=labels[:7])
    bst = xgb.train(param, dtrain)

    # Combine data and labels and select rows together
    newdf = df.copy()
    newdf["labels"] = labels
    ddf = dd.from_pandas(newdf, npartitions=4)
    ddf_trimmed = ddf[ddf.x < 8]

    # Split data and labels back apart
    ddf_train = ddf_trimmed.drop("labels", axis=1)
    ddf_labels = ddf_trimmed["labels"]

    # Train in dask-xgboost with trimmed data (fails with distributed cluster!)
    dbst = yield dxgb._train(c, param, ddf_train, ddf_labels)

    result = bst.predict(dtrain)
    dresult = dbst.predict(dtrain)

    correct = (result > 0.5) == labels[:7]
    dcorrect = (dresult > 0.5) == labels[:7]
    assert dcorrect.sum() == correct.sum()
```

**Comment by mrphilroth** [comment]
Still tracking this down. It works when I start workers from the command line on the same machine. It does not work when I use command line workers on two different machines. It gives me the same error on the scheduler as above, but since I'm using the command line workers I can get new error messages from workers that aren't local to the scheduler:

```
distributed.protocol.pickle - INFO - Failed to deserialize b"\x80\x04\x95\xc9\x03\x00\x00\x00\x00\x00\x00(\x8c\ndask.utils\x94\x8c\x0cmethodcaller\x94\x93\x94\x8c\x05apply\x94\x85\x94R\x94]\x94(\x8c/('getitem-b9a4e72ddad1ca8e3fa063ede97f4f79', 4)\x94\x8c\x17cloudpickle.cloudpickle\x94\x8c\x0e_fill_function\x94\x93\x94(h\x08\x8c\x0f_make_skel_func\x94\x93\x94h\x08\x8c\r_builtin_type\x94\x93\x94\x8c\x08CodeType\x94\x85\x94R\x94(K\x01K\x00K\x01K\x04KSC\x1bt\x00\x00|\x00\x00d\x04\x00d\x00\x00\x85\x02\x00\x19d\x02\x00\x83\x02\x00d\x03\x00\x16S\x94(NK\x03K\x10K\x05J\xfd\xff\xff\xfft\x94\x8c\x03int\x94\x85\x94\x8c\x03sha\x94\x85\x94\x8c\x1edistributed_train_dataframe.py\x94\x8c\x08<lambda>\x94KUC\x00\x94))t\x94R\x94J\xff\xff\xff\xff}\x94\x87\x94R\x94}\x94N}\x94\x8c\x08__main__\x94NtR\x88)e}\x94\x8c\x12pandas.core.series\x94\x8c\x06Series\x94\x93\x94)\x81\x94}\x94(\x8c\x05_data\x94\x8c\x15pandas.core.internals\x94\x8c\x12SingleBlockManager\x94\x93\x94)\x81\x94(]\x94\x8c\x18pandas.core.indexes.base\x94\x8c\n_new_Index\x94\x93\x94\x8c\x19pandas.core.indexes.range\x94\x8c\nRangeIndex\x94\x93\x94}\x94(\x8c\x05start\x94K\x00\x8c\x04name\x94N\x8c\x04stop\x94K\x00\x8c\x04step\x94K\x01u\x86\x94R\x94a]\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x00\x85\x94\x8c\x05numpy\x94\x8c\x05dtype\x94\x93\x94\x8c\x02i8\x94K\x00K\x01\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x00\x94t\x94ba]\x94h1\x8c\x1bpandas.core.indexes.numeric\x94\x8c\nInt64Index\x94\x93\x94}\x94(h7N\x8c\x04data\x94h?hBK\x00\x85\x94hD\x87\x94R\x94(K\x01K\x00\x85\x94hM\x89hPt\x94bu\x86\x94R\x94a}\x94\x8c\x060.14.1\x94}\x94(\x8c\x06blocks\x94]\x94}\x94(\x8c\x08mgr_locs\x94h?hBK\x00\x85\x94hD\x87\x94R\x94(K\x01K\x00\x85\x94hM\x89hPt\x94b\x8c\x06values\x94hFua\x8c\x04axes\x94h.ust\x94bh7N\x8c\x04_typ\x94\x8c\x06series\x94\x8c\t_metadata\x94]\x94h7aubt\x94."
Traceback (most recent call last):
  File "/home/proth/.conda/envs/dask/lib/python3.5/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
TypeError: _fill_function() takes 5 positional arguments but 6 were given
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/home/proth/.conda/envs/dask/lib/python3.5/site-packages/distributed/worker.py", line 1241, in add_task
    self.tasks[key] = _deserialize(function, args, kwargs, task)
  File "/home/proth/.conda/envs/dask/lib/python3.5/site-packages/distributed/worker.py", line 658, in _deserialize
    args = pickle.loads(args)
  File "/home/proth/.conda/envs/dask/lib/python3.5/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
TypeError: _fill_function() takes 5 positional arguments but 6 were given
```

Still working on it, but if this looks familiar to anyone I'd love to know.

**Comment by mrocklin** [comment]
Given the error my first guess is a difference in library versions somewhere.  Perhaps `_fill_function` takes five or six arguments in different versions of the same library.

**Comment by mariusvniekerk** [comment]
So there has been some activity in cloud pickle. I'd validate that all your nodes are running the same /latest? Version

**Comment by mrphilroth** [comment]
Yep. Versions. I did a deep clean on my local conda environment. I must have had something old in there that was different from what was getting provisioned on EC2 nodes. Thanks.
