### ISSUE TITLE
xgboost not running when not using LocalCluster

### ISSUE THREAD

**Issue by sagnik-rzt** [dask/dask-xgboost#19]
Hey guys, I am trying to run a distributed xgboost model on dask. I am able to run it using a ```LocalCluster()```, however when I manually set up my scheduler and worker and use a ```Client``` pointing towards that scheduler, I hit some exceptions. This is my code:
```
from dask.distributed import Client
import dask.dataframe as dd

client = Client('192.168.49.37:8786')
client.restart()

df = dd.read_csv("adult_comp_cont", storage_options={'anon' : True})
df = df[:100]
df.columns = [str(i) for i in range(6)] + ['target']
Y = client.persist(df['target'])
X = client.persist(df.drop('target', axis=1))

import dask_xgboost as dxgb
params = {'objective' :'binary:logistic', 'n_estimators' : 10, 'max_depth' : 3, 'learning_rate' : 0.033}
bst = dxgb.train(client, params, X, Y)
print("Predicted!")

```
The exception I am getting is:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/dask_xgboost/core.py", line 116, in _train
    worker_map[first(workers)].append(key_to_part_dict[key])
  File "/usr/local/lib/python3.5/dist-packages/toolz/itertoolz.py", line 368, in first
    return next(iter(seq))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sagnikb/PycharmProjects/auto_ML/test_dask_distributed.py", line 15, in <module>
    bst = dxgb.train(client, params, X, Y)
  File "/usr/local/lib/python3.5/dist-packages/dask_xgboost/core.py", line 169, in train
    labels, dmatrix_kwargs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/distributed/utils.py", line 253, in sync
    six.reraise(*error[0])
  File "/home/sagnikb/.local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
RuntimeError: generator raised StopIteration

Process finished with exit code 1

```
This is my scheduler log:
```
(dask)bblite@MasterNode >>>>  source dask/bin/activate && dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:  tcp://192.168.49.37:8786
distributed.scheduler - INFO - Local Directory:    /tmp/scheduler-otyb311x
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Register tcp://192.168.49.38:34850
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.49.38:34850
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-3fecd394-79cf-11e8-9d33-945330cf5663
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Send lost future signal to clients
distributed.scheduler - INFO - Remove worker tcp://192.168.49.38:34850
distributed.core - INFO - Removing comms to tcp://192.168.49.38:34850
distributed.scheduler - INFO - Lost all workers
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO - Register tcp://192.168.49.38:41151
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.49.38:41151
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO - Remove client Client-3fecd394-79cf-11e8-9d33-945330cf5663
distributed.scheduler - INFO - Close client connection: Client-3fecd394-79cf-11e8-9d33-945330cf5663

```
This is my worker log:
```
(dask)bblite@WorkerNode1:~$ source dask/bin/activate && dask-worker 192.168.49.37:8786
distributed.nanny - INFO -         Start Nanny at: 'tcp://192.168.49.38:39734'
distributed.worker - INFO -       Start worker at:  tcp://192.168.49.38:34850
distributed.worker - INFO -          Listening to:  tcp://192.168.49.38:34850
distributed.worker - INFO -              nanny at:        192.168.49.38:39734
distributed.worker - INFO - Waiting to connect to:   tcp://192.168.49.37:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          8
distributed.worker - INFO -                Memory:                   16.83 GB
distributed.worker - INFO -       Local Directory: /home/bblite/dask-worker-space/worker-bwwa2seh
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://192.168.49.37:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Stopping worker at tcp://192.168.49.38:34850
distributed.worker - INFO -       Start worker at:  tcp://192.168.49.38:41151
distributed.worker - INFO -          Listening to:  tcp://192.168.49.38:41151
distributed.worker - INFO -              nanny at:        192.168.49.38:39734
distributed.worker - INFO - Waiting to connect to:   tcp://192.168.49.37:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          8
distributed.worker - INFO -                Memory:                   16.83 GB
distributed.worker - INFO -       Local Directory: /home/bblite/dask-worker-space/worker-mqcum0th
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://192.168.49.37:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - WARNING -  Compute Failed
Function:  read_block_from_file
args:      (<dask.bytes.core.OpenFile object at 0x7f9f01355978>, 0, 64000000, b'\n')
kwargs:    {}
Exception: FileNotFoundError(2, 'No such file or directory')
```
Is anyone else facing this issue? Thanks in advance.

**Comment by TomAugspurger** [comment]
```
distributed.worker - WARNING -  Compute Failed
Function:  read_block_from_file
args:      (<dask.bytes.core.OpenFile object at 0x7f9f01355978>, 0, 64000000, b'\n')
kwargs:    {}
Exception: FileNotFoundError(2, 'No such file or directory')
```

makes me suspect that this is purely related to dask, not dask-xgboost. It seems like the worker isn't able to get the data.

What is `adult_comp_cont`? Is that supposed to be a path to an S3 file? The workers would all need access to a shared file system of some sort.

**Comment by mrocklin** [comment]
Ideally the client would receive this exception when the run dask_xgboost
code.  Currently we wait on all of the parts of the dataframe, but we don't
verify that they succeeded.  Instead we should probably verify that all of
them have finished and, if any didn't, we should raise an error.  I can
throw up a quick PR.

But yes, as to the original question, the file isn't available on the other
workers.

**Comment by sagnik-rzt** [comment]
Ahh got it. The file was present on the master node only, so workers didn't have access to it. Thanks a lot!
